name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE [(#$NUMBER)]($URL) @$AUTHOR'
references:
  - main
  - v.+
exclude-labels:
  - 'skip-changelog'
categories:
  - title: 'Features 🚀'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes 🐛'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance 🧰'
    label: 
      - 'chore'
      - 'deps'
version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking-change'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feat'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'perf'
      - 'performance'
  default: patch
template: |
  ## Changelog
  
  Love this little Action? Let me know, or donate some tea money.
  
  **An update from `$PREVIOUS_TAG`**
  
  
  $CHANGES
  
  
  ### Reporting errors:
  Does this release break your workflow?
  [Create an issue]() stat! Chances are you aren't the only
  one running into that issue. It'll help others find possible
  solutions while notifying me (Daniel Tamkin) of any problems.